### ISSUE TITLE
rename master branch

### ISSUE THREAD

**Issue by brentzundel** [hyperledger/indy-node#1606]
# Summary
We should rename the branch `master` to `main` and use that going forward for our work.

From [Problematic Terminology in Open-Source](https://blog.carbonfive.com/2018/10/08/problematic-terminology-in-open-source/) on master/slave terminology in software:

> Use of this term is problematic. It references slavery to convey meaning about the relationship between two entities.

Removing this terminology from our workflow is a small gesture to include more people from marginalized groups in this project.

(I’m open to names other than `main`)

## Technical Steps

- [x]  create main branch from master
- [x]  make main the default GitHub branch
- [x]  modify github/central to use main for release notes reloading
- [x]  redirect PRs to main in hyperledger/indy-node
- [x]  move branch protections from master to main
- [x]  modify docs to reference main instead of master
- [x]  delete master branch to avoid confusion?

Feedback?

**Comment by dhh1128** [comment]
I am in favor of this change.

**Comment by brentzundel** [comment]
I have heard that github is working on tools to simplify this. It may be best to wait until those are available.
But if they aren't available within a couple of months I'd like to proceed.
