### ISSUE TITLE
Updated Dev Setup

### ISSUE THREAD

**Issue by JakeFromIBM** [hyperledger/indy-node#1609]
Is there a more up-to-date setup guide for developers? 
The one [here]( https://github.com/hyperledger/indy-node/blob/master/docs/source/setup-dev.md) seems like it's very outdate. (e.g., tells you to use indy-crypto but it looks like Ursa is used instead)

**Comment by dhh1128** [comment]
Comment from @brentzundel : I made several changes to the dev setup instructions when I raised [my PR to remove indy-crypto](https://github.com/hyperledger/indy-node/pull/1607) that may address this issue if it gets reviewed and merged.
