### ISSUE TITLE
suggestion  in  naming 

### ISSUE THREAD

**Issue by SalimiHabib** [hyperledger/indy-node#1615]
Perhaps the second line makes it easier to define the concept

1- There is an **indy ledger** that contains several **ledger** included **audit ledger** , **config ledger** and ... 
2- There is an **indy ledger** that contains several **sub ledger**  included **audit sub ledger** , **config sub ledger** and ... 

thank you

**Comment by dhh1128** [comment]
Yes, I think your verbiage is an improvement. What document are you suggesting we update?
