### ISSUE TITLE
Error while creating pool using indy-cli 

### ISSUE THREAD

**Issue by HarshMultani** [hyperledger/indy-node#1623]
I have ran the indy_pool network and it is up using the command : docker run -itd -p 9701-9708:9701-9708 indy_pool

Now, I have installed indy-cli in my system

Now when I am trying to create a pool using the command: 
pool create local_pool gen_text_file=/<PATH_TO_INDY_SDK>/indy-sdk/cli/docker_pool_transactions_genesis

It is giving me the error : 
Unknown "gen_text_file" parameter present

Can someone explain why is this issue coming and what can be done to resolve this?

**Comment by WadeBarnes** [comment]
The parameter should be `gen_txn_file`.

To list the help for the command in the `cli`:
```
indy> pool create help
Command:
        pool create - Create new pool ledger config with specified name

Usage:
        pool create <name-value> gen_txn_file=<gen_txn_file-value>

Parameters are:
        name - The name of new pool ledger config
        gen_txn_file - Path to file with genesis transactions

Examples:
        pool create pool1 gen_txn_file=/home/pool_genesis_transactions
```

**Comment by HarshMultani** [comment]
Hi, I gave the location of the genesis file for the network...  still it was not working.   But anyhow, after some time it worked.
