### ISSUE TITLE
Documentation to run a production indy network with governance in place.

### ISSUE THREAD

**Issue by georgepadayatti** [hyperledger/indy-node#1625]
There should be proper documentation provided to run production capable indy network and guidance on governance capabilities. It should be structured in such a way that any entity should be equipped to run their own indy network. Current documentation is very much scattered, that an entity would have to rely on third parties to understand the steps. Proper documentation is very much required if we have to spread the SSI movement across boundaries.

**Comment by darkchylde** [comment]
This would help in creating small indy networks in different parts of the world, and when the interoperability project succeeds, it will connect these networks creating a powerful alternative to PKI.

**Comment by ggold7046** [comment]
Hi @georgepadayatti , could you please guide me more on how to solve this issue  ?

**Comment by WadeBarnes** [comment]
@georgepadayatti, @ggold7046, I believe this documentation covers this issue.  There is a bit of clean-up but it covers creating a new network. https://github.com/hyperledger/indy-node/pull/1814

**Comment by georgepadayatti** [comment]
> Hi @georgepadayatti , could you please guide me more on how to solve this issue  ?

Hi there, do go through the PR referenced by @WadeBarnes in the comment. 

I have also created a node operator guide available at https://github.com/decentralised-dataexchange/nordxdataspace/blob/main/docs/node-operator-guide.md

Please feel free to go through the guide, raise issues. I can try to answer them. 

Hope this helps.

**Comment by georgepadayatti** [comment]
> @georgepadayatti, @ggold7046, I believe this documentation covers this issue.  There is a bit of clean-up but it covers creating a new network. https://github.com/hyperledger/indy-node/pull/1814
> 
> 

Will definitely check this out.
