### ISSUE TITLE
Fix broken Indy Node CD pipeline

### ISSUE THREAD

**Issue by skhoroshavin** [hyperledger/indy-node#1629]
Merging changes with moving from Indy Crypto to Ursa (see this PR: https://github.com/hyperledger/indy-node/pull/1607) has broken Indy Node CD pipeline. This needs to be fixed, because it would block any further releases (and frankly doing general development work is also quite hard in this situation)

**Acceptance criteria**
* Indy Node should have green CD pipeline in master

**Comment by WadeBarnes** [comment]
What do we need to do to move this forward?

**Comment by pSchlarb** [comment]
As the acceptance criteria is matched, this issue will be closed.
