### ISSUE TITLE
Cannot build dockers

### ISSUE THREAD

**Issue by radiantone** [hyperledger/indy-node#1630]
Running pool_start kicks off a docker build for the nodes that fails.

Running on Ubuntu 20.04

The following packages have unmet dependencies:
 indy-node : Depends: indy-plenum (= 1.13.0~dev1024) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by fariduca** [comment]
I am facing the same problem. Is there a solution yet?

**Comment by WadeBarnes** [comment]
Closing for now.  Please reopen if this continues to be an issue.
