### ISSUE TITLE
Update base docker images to 20.04

### ISSUE THREAD

**Issue by radiantone** [hyperledger/indy-node#1631]
Currently, indy node bases its docker images off ubuntu 16.04. this version is no longer supported.

Please update them to use 20.04

**Comment by swcurran** [comment]
We have an initiative to do this, but the work is not yet complete.

Note that Support continues for Ubuntu 16.04 through April 2021 (per https://wiki.ubuntu.com/Releases), so we still have a short period of time to complete the upgrade.

**Comment by solidnerd** [comment]
@swcurran Are there any updates on the topic ?

**Comment by swcurran** [comment]
The team is still working on the CI/CD work that is a pre-requisite for the Ubuntu upgrade.

**Comment by ldsenow** [comment]
This is why I wasn't able to create a pool. I tried ubuntu 20.04 and 18.04 and neither of them worked.

**Comment by pSchlarb** [comment]
This issue should have been resolved with the pipeline and devcontainer work for the ubuntu-20.04-upgrade branch.
