### ISSUE TITLE
Ensure technical policies already enable the extraction of additional metrics for `validator-info`

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/indy-node#1672]
- [Add more detailed hardware metrics to the collection and output of `validator-info`](https://github.com/hyperledger/indy-node/issues/1669)
- [Add additional resource and system metrics to the collection and output of `validator-info`](https://github.com/hyperledger/indy-node/issues/1670)

**Comment by WadeBarnes** [comment]
@lohanspies, Who is best equipped to start this investigation, and where is the relevant resource material?

**Comment by lohanspies** [comment]
@WadeBarnes I can take an initial look at the [tech check script ](https://github.com/sovrin-foundation/steward-tools/blob/master/steward_tech_check.py)and revert. Assume that the implementation will need to be in `indy-vdr`?

**Comment by WadeBarnes** [comment]
> @WadeBarnes I can take an initial look at the [tech check script ](https://github.com/sovrin-foundation/steward-tools/blob/master/steward_tech_check.py)and revert.

@lohanspies, Ah, sorry, I was thinking this was a governance policy item.  If it's simple a question of whether it's technically possible to collect the information from a node and include it the the response, the answer is Yes.

**Comment by lohanspies** [comment]
@WadeBarnes we can close this ticket and focus on implementing as per the current technical requirements. If the technical policy changes later on we can adapt.
