### ISSUE TITLE
Setup Hyperledger Artifactory repositories for publishing release artifacts

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/indy-node#1675]
`indy-node` and `indy-plenum` artifacts have up until now been published to https://repo.sovrin.org/, using the Sovrin hosted Jenkins CI/CD environment.  As part of the migration to the GitHub actions based CI/CD process we are also migrating over to the Hyperledger Artifactory hosted environment for publishing the artifacts generated by the new pipelines.

**Only Hyperledger artifacts will be hosted in the new repository.  Related Sovrin packages will continue to live in `repo.sovrin.org`**

References:
- [Debian Repositories](https://www.jfrog.com/confluence/display/JFROG/Debian+Repositories)
- [Signing Keys Management](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Security#ArtifactorySecurity-SigningKeysManagement)
- [Setup JFrog CLI](https://github.com/marketplace/actions/setup-jfrog-cli)
- [JFrog Access Tokens](https://www.jfrog.com/confluence/display/JFROG/Access+Tokens)
- [Repository Layouts](https://www.jfrog.com/confluence/display/JFROG/Repository+Layouts)
- https://hyperledger.jfrog.io/ui/repos/tree/General/artifactory-build-info

Example for current repo structure:
- https://repo.sovrin.org/deb/pool/xenial/rc/i/indy-node/
- https://repo.sovrin.org/deb/pool/xenial/stable/i/indy-node/
- https://repo.sovrin.org/lib/apt/xenial/rc/
- https://repo.sovrin.org/lib/apt/xenial/stable/
- https://repo.sovrin.org/lib/apt/xenial/master/
- http://ftp.debian.org/debian/

Additional Resources:
- Example of publishing a Docker image to Hyperledger Artifactory: https://github.com/hyperledger/besu/blob/a58c472480a46a4020383e264fed61e20a05bee4/.circleci/config.yml#L224-L248
- [webfactory/ssh-agent](https://github.com/marketplace/actions/webfactory-ssh-agent)
- [Import GPG](https://github.com/marketplace/actions/import-gpg)
- [Hosting your own PPA repository on GitHub](https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html)

Debian Documntion:
- [SecureApt](https://wiki.debian.org/SecureApt)
- [7.5. Package signing in Debian](https://www.debian.org/doc/manuals/securing-debian-manual/deb-pack-sign.en.html)

New Hyperledger Indy Repository:
- [Hyperledger Indy Repository](https://hyperledger.jfrog.io/artifactory/indy/)

Process Summary for setting up the deployment configurations for use with [Setup JFrog CLI](https://github.com/marketplace/actions/setup-jfrog-cli):
- Created a new `indy-cd` user with only profile edit permissions.
- Created an `indy-publishers` group,  `indy-cd` user is a member.
- Created an `indy-deploy` permission that provides the `indy-publishers` group with Deploy permissions to the `indy` Artifactory Repository.
- Generated a private api-key for the `indy-cd` user.
- Created a new config using the `jfrog-cli` containing the `indy-cd` user's token.
- Exported the resulting configuration token to be mounted in GitHub as a secret (`INDY_ARTIFACTORY_REPO_CONFIG`).

**Comment by WadeBarnes** [comment]
@udosson, We can discuss the setup of the publishing repos here.

**Comment by udosson** [comment]
@WadeBarnes 
How if we use the Github Action [Setup JFrog CLI](https://github.com/marketplace/actions/setup-jfrog-cli) and then upload artifacts with JFrog CLI as the following?
jfrog rt u --deb=xenial/stable/amd64 indy-node_1.12.4_amd64.deb debian-repo/pool/stable/indy/indy-node_1.12.4_amd64.deb

**Comment by udosson** [comment]
Next steps to do:
- set up Hyperledger Fabric Artifactory
- Store credential as secrets in GitHub (maybe Server ID of Artifactory as well)
- Evaluate uploading method (JFrog CLI vs. CURL)
- Implement signing of packages with gpg (Take a look at [Import GPG](https://github.com/marketplace/actions/import-gpg))
- Upload can be tested with [local Debian repository](https://www.jfrog.com/confluence/display/JFROG/Debian+Repositories)

**Comment by WadeBarnes** [comment]
@udosson, It looks like Artifactory can handle the GPG key management and signing.

**Comment by WadeBarnes** [comment]
> Next steps to do:
> 
> * set up Hyperledger Fabric Artifactory

It will be an **Indy** repository.

**Comment by WadeBarnes** [comment]
@udosson,

I've created the new repo here and uploaded the current `rc` and `stable` versions of `indy-node` and `indy-plenum` to test things out, and play with the repository structure.  I still have to setup the permissions, tokens, and keys.

- jFrog UI: https://hyperledger.jfrog.io/ui/repos/tree/General/indy
- Resulting repository: https://hyperledger.jfrog.io/artifactory/indy/

The `pool/*` directory is where the packages get uploaded.  The `dists` directory and content is auto-generated.

Do you have any opinion on the structure we should use in the `pool/*` directory?

**Comment by WadeBarnes** [comment]
> @udosson, It looks like Artifactory can handle the GPG key management and signing.

The built in key management does not work as expected.  I don't think it will suit your needs.

**Comment by WadeBarnes** [comment]
The single GPG key managed by Artifactory is used to support [SecureApt](https://wiki.debian.org/SecureApt).

**Comment by WadeBarnes** [comment]
Based on this information we should move forward with the supported **SecureApt** configuration.  This also simplifies things since we no longer have to sign the individual deb packages.

@askolesov, @udosson, @ryjones, Thoughts, comments?

**Comment by WadeBarnes** [comment]
@ryjones, Given this is a Hyperledger repository, the GPG key for the repository should be issued and managed by Hyperledger.  Would you agree?  That way any other repositories that get hosted will be protected (signed) by the same key.

**Comment by ryjones** [comment]
I agree - we need to decide how to do that

**Comment by WadeBarnes** [comment]
DMed you links describing the process, and to the place in Artifactory where the key needs to be installed.

**Comment by WadeBarnes** [comment]
@udosson, The configuration needed for [Setup JFrog CLI](https://github.com/marketplace/actions/setup-jfrog-cli) to publish packages to the Indy Artifactory repository has been mounted on the `indy-node` and `indy-plenum` GitHub repositories as `INDY_ARTIFACTORY_REPO_CONFIG`.  Thanks for doing that @ryjones.

@ryjones is in the process of setting up and installing the GPG signing key for the Artifactory server.  Once that's in place and we've run some tests with GitHub actions we'll clear out all of the test packages and start clean.

**Comment by WadeBarnes** [comment]
`INDY_ARTIFACTORY_REPO_CONFIG` secrets are set.  GPG signing key installed.

I've cleared out the repository and re-uploaded the 1.12.4 set of `rc` and `stable` releases using the Debian `pool` directory layout convention.

Commands used to upload the packages (from local command line):
```
jfrog rt u --deb xenial/stable/amd64 .\stable\indy-node_1.12.4_amd64.deb indy/pool/stable/i/indy-node/indy-node_1.12.4_amd64.deb
jfrog rt u --deb xenial/stable/amd64 .\stable\indy-plenum_1.12.4_amd64.deb indy/pool/stable/i/indy-plenum/indy-plenum_1.12.4_amd64.deb
jfrog rt u --deb xenial/rc/amd64 .\rc\indy-node_1.12.4_rc1_amd64.deb indy/pool/rc/i/indy-node/indy-node_1.12.4_rc1_amd64.deb
jfrog rt u --deb xenial/rc/amd64 .\rc\indy-plenum_1.12.4_amd64.deb indy/pool/rc/i/indy-plenum/indy-plenum_1.12.4_amd64.deb
```

**Note:**
For the Unbuntu 20.04 releases the `--deb` option would use `focal` in place of `xenial`.

Next steps:
- Test out [Setup JFrog CLI](https://github.com/marketplace/actions/setup-jfrog-cli) in the CD workflow of `indy-plenum` or `indy-node`.

**Comment by ryjones** [comment]
OK - I think my work here is done

**Comment by WadeBarnes** [comment]
Thanks @ryjones

**Comment by udosson** [comment]
> @udosson,
> 
> I've created the new repo (links below) and manually (via the UI) uploaded the current `rc` and `stable` versions of `indy-node` and `indy-plenum` to test things out and play with the repository structure. I still have to setup the permissions, tokens, and keys.
> 
> * jFrog UI: https://hyperledger.jfrog.io/ui/repos/tree/General/indy
> * Resulting repository: https://hyperledger.jfrog.io/artifactory/indy/
> 
> The `pool/*` directory is where the packages get uploaded. The `dists` directory and content is auto-generated.
> 
> Do you have any opinion on the structure we should use in the `pool/*` directory?

Hi @WadeBarnes, would it make sense to create the same subdirectoy structure in `pool` as in `dists`?
e.g.:
`indy/dists/xenial/stable/binary-amd64` and `indy/pool/xenial/stable/i/indy-plenum/`

**Comment by WadeBarnes** [comment]
@udosson, We should keep the `distribution` name out of the `pool` path.  It's possible that a single package could support more than one `distribution`.  That can be specified when the package is published and Artifactory will index it accordingly (create the required `dist` folders referencing the single package in the `pool` automatically).

**Comment by WadeBarnes** [comment]
This is done.  The first official GHA build artifact from the main branch of indy-plenum was published today:
- https://github.com/hyperledger/indy-plenum/actions/runs/1005754452
- https://hyperledger.jfrog.io/ui/repos/tree/General/indy/pool/main/i/indy-plenum/indy-plenum_1.13.0~dev82_amd64.deb

Many more great things to come.
