### ISSUE TITLE
Ubuntu 20.04: create CI for Ubuntu 20.04

### ISSUE THREAD

**Issue by Toktar** [hyperledger/indy-node#1678]
Create CI for Ubuntu 20.04 for a feature brunch `ubuntu-20.04-upgrade`

**Acceptance criteria:**
- All existing tests are launched via GitHub Actions, and they pass (if pass locally)
- All jobs(steps) pass
- Reports from launches are available.

**Comment by WadeBarnes** [comment]
The initial (16.04) GHA based CI workflow is working here; https://github.com/WadeBarnes/indy-node/actions/runs/1006012413
- Based on the same work done in [hyperledger/indy-plenum](https://github.com/hyperledger/indy-plenum)
- Once complete, this will be integrated into the `ubuntu-20.04-upgrade` branch.

**Comment by WadeBarnes** [comment]
PR for initial (16.04) GHA based CI workflow is working here; https://github.com/hyperledger/indy-node/pull/1680

**Comment by pSchlarb** [comment]
As  #1697 is already merged, can this Issue be closed?
