### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mwherman2000** [hyperledger/indy-node#1683]
On this page:
https://hyperledger-indy.readthedocs.io/projects/node/en/latest/requests.html
there are several occurrences of this link:
https://github.com/hyperledger/indy-node/blob/master/docs/source/auth_rules
...and it does not exist.

**Comment by WadeBarnes** [comment]
Based on the context, it looks like the link was meant to be; https://github.com/hyperledger/indy-node/blob/master/docs/source/auth_rules.md

**Comment by esplinr** [comment]
The ReadTheDocs documentation was created by a student contributor, and has not been maintained.

**Comment by mwherman2000** [comment]
> The ReadTheDocs documentation was created by a student contributor, and has not been maintained.

Is this considered the official (or only significant) documentation on Indy?

**Comment by swcurran** [comment]
The official documentation in the indy-node and indy-sdk repos.  The readthedocs is published from the materials in the repo.

**Comment by mwherman2000** [comment]
What I was getting at is that if this is the (only) official documentation of the platform, it should/needs to be maintained ...and not left to whither ...unless you want the entire platform to whither.

**Comment by swcurran** [comment]
Please go ahead.
