### ISSUE TITLE
Error in "Setting up a new network" document

### ISSUE THREAD

**Issue by lynnbendixsen** [hyperledger/indy-node#1733]
There have been at  least 2 people that have recently asked me questions related to this issue, so I looked into it and discovered the following:

In step IV of https://github.com/hyperledger/indy-node/blob/master/docs/source/NewNetwork/NewNetwork.md there is a step which says that the user must create a directory (using new network name) in order to copy in the genesis files.  But the directory it mentions must already have been created during step III.2 before the Steward ran init_indy_node, or their keys will not have been created in the right place.  @pSchlarb I will have a deeper look at this tomorrow and see if I can get a PR put in that will help alleviate the confusion.  
This confusion surrounding this issue has also expanded to another document. The Hands On Walkthrough also needs repaired to reflect the above. (Steps 8 and 9 must be moved to Before step 5)  It will not work as it currently written.

**Comment by WadeBarnes** [comment]
Step `III.2.i` talks about the need to substitute the new network name in the appropriate places in the [Installation and configuration of Indy-Node](https://github.com/hyperledger/indy-node/blob/master/docs/source/installation-and-configuration.md) guide.  Though it would be a good idea to then highlight those areas in the guide itself.  e.g. Highlight the areas with "**This is where you would substitute the name of the network if you were setting up a new network.**"

The steps are definitely out of order in the [Hands on Walkthrough](https://github.com/hyperledger/indy-node/blob/master/sample/Network/README.md).

**Comment by lynnbendixsen** [comment]
Created a PR for this:  https://github.com/hyperledger/indy-node/pull/1734

**Comment by lynnbendixsen** [comment]
PR was accepted.  Closing the issue.
