### ISSUE TITLE
What happens if the DID Core context changes?

### ISSUE THREAD

**Issue by cjhowland** [hyperledger/indy-node#1739]
> [10.1.3 DIDDoc Assembly Steps](https://hyperledger.github.io/indy-did-method/#diddoc-assembly-steps)
3.2: If the diddocContent item contains a @context item, the DIDDoc is assumed to be JSON-LD, and the @context element MUST include the current DID Core JSON-LD context. If it does not, exit the assmebly process and return an error.

Wouldn't this check require updating the ledgers in the event that the DID Core `@context` is revised? This dependency may cause issues if there is a version or domain name change. In anticipation of future revisions, perhaps it is preferable to leave this check to the creator of the `diddoc_content`.

**Comment by dbluhm** [comment]
This issue should be opened in the indy-did-method repo :slightly_smiling_face:
