### ISSUE TITLE
Ubuntu 20.04 based nodes intermittently loose consensus when running on a network with Ubuntu 16.04 based nodes

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/indy-node#1750]
Some investigation into this has been done and documented here; https://hackmd.io/GSJnYPt0Q9yFKgoNGWtcMw

[hyperledger/indy-node-container](https://github.com/hyperledger/indy-node-container) would provide a good resource for creating an environemnt where this issue can be replicated.
- It contains a Dockerfile for a 20.04 node; https://github.com/hyperledger/indy-node-container/blob/main/build/Dockerfile.ubuntu20
  - The file should be updated to use a newer version of the indy-node release.  The latest (at the time of writing) is https://hyperledger.jfrog.io/ui/repos/tree/General/indy/pool/focal/dev/i/indy-node/indy-node_1.13.0~dev24_amd64.deb.  The `dev` version git reset due to refactoring of the automated release processes.

As discussed on the 2022-05-10 Indy Contributors Call, we need to have a way to reliably replicate the issue so we can troubleshoot and fix the underlying problem; https://wiki.hyperledger.org/display/indy/2022-05-10+Indy+Contributors+Call

**Comment by c2bo** [comment]
I guess we can close this? @WadeBarnes

**Comment by pSchlarb** [comment]
I think so too. If something was missing, we can still reopen it.
