### ISSUE TITLE
Not able to install this module for ubuntu2004 branch

### ISSUE THREAD

**Issue by Aashish07** [hyperledger/indy-node#1757]
The documnet is outdated even when this has been going on for a month. Please help me out , or update the document so that we can what updates are there. Need to install this on ubuntu 20.04 lts asap. @shemnon @redongjun @m00sey @trentlarson @peacekeeper

**Comment by pSchlarb** [comment]
First of all what document is outdated?
Which module is not installable?
Have you checked the `ubuntu-20.04-upgrade` branch?
Have your read the [NewNetwork Documentation](https://github.com/hyperledger/indy-node/blob/master/docs/source/NewNetwork/NewNetwork.md) ?

**Comment by Aashish07** [comment]
@WadeBarnes Extremely sorry for delay,
@pSchlarb  Yes I have checked out the branch ubuntu-20.04-upgrade , 
And i am talking about this documentation -> 
https://github.com/hyperledger/indy-node/blob/ubuntu-20.04-upgrade/docs/source/setup-dev.md
I can see that i can build and install the module directly using pip for which it will download all the whl file, 
(As it happens in aries agent) -> pip install -e . (As mentioned in the above document).
but it gives error. I am attaching the snippet for the same .  Please help if you can. 

`sudo apt-get install indy-node
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indy-node : Depends: indy-plenum (= 1.12.4) but it is not going to be installed
             Depends: python3-distro (= 1.3.0) but 1.4.0-1 is to be installed
             Depends: libsodium18 but it is not installable
E: Unable to correct problems, you have held broken packages.
`

**Comment by pSchlarb** [comment]
@Aashish07 I checked the [Gitpod Image](https://github.com/hyperledger/indy-node/blob/ubuntu-20.04-upgrade/.gitpod.Dockerfile) and the [local vscode devcontainer image](https://github.com/hyperledger/indy-node/blob/ubuntu-20.04-upgrade/.devcontainer/Dockerfile). Both are working. They are able to install it without any problems. 


> I can see that i can build and install the module directly using pip for which it will download all the whl file,
(As it happens in aries agent) -> pip install -e . (As mentioned in the above document).

Not sure if you meant installing the local(cloned) folder with `-e, --editable` or installing from pypi.

The documentation [setup-dev.md](https://github.com/hyperledger/indy-node/blob/ubuntu-20.04-upgrade/docs/source/setup-dev.md) describes setting up a development environmet, to work on the indy-node code.

Installing from Pypi or apt is meant for "production" use of indy-node.
Also from the view of pypi the last stable release (1.12.4) is still meant for ubuntu16.04.

> ERROR: Failed building wheel for python-rocksdb
Running setup.py clean for python-rocksdb
Failed to build python-rocksdb
ERROR: aries-cloudagent 0.7.4rc2 has requirement prompt-toolkit~=2.0.9, but you'll have prompt-toolkit 3.0.29 which is incompatible.
ERROR: aries-cloudagent 0.7.4rc2 has requirement rlp==0.5.1, but you'll have rlp 0.6.0 which is incompatible.
Installing collected packages: python-rocksdb, orderedset, psutil, pympler, semver, rlp, ujson, ioflo, sortedcontainers, msgpack-python, leveldb, sha3, prompt-toolkit, indy-plenum, timeout-decorator, indy-node
Running setup.py install for python-rocksdb ... error

It also seems that your machine is very unhappy to have aries installed AND trying to install indy-node ;)

As a matter of fact installing indy-node ([latest prerelease](https://pypi.org/project/indy-node/1.13.0.dev1654241043/)) from pypi on a clean ubuntu20.04 container throws the exact same error when building rocksdb:
>   cythoning rocksdb/_rocksdb.pyx to rocksdb/_rocksdb.cpp
  /tmp/pip-install-99a8sb8p/python-rocksdb/.eggs/Cython-0.29.30-py3.8-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-99a8sb8p/python-rocksdb/rocksdb/_rocksdb.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'rocksdb._rocksdb' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/rocksdb
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c rocksdb/_rocksdb.cpp -o build/temp.linux-x86_64-3.8/rocksdb/_rocksdb.o -std=c++11 -O3 -Wall -Wextra -Wconversion -fno-strict-aliasing -fno-rtti
  rocksdb/_rocksdb.cpp:722:10: fatal error: rocksdb/slice.h: No such file or directory
    722 | #include "rocksdb/slice.h"
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-rocksdb
 
The containers install python rocksdb via apt and the sovrin repos.
https://github.com/hyperledger/indy-node/blob/59bb3a95784e2a45283c634ec0c716c50520364c/.gitpod.Dockerfile#L29-L32
and
https://github.com/hyperledger/indy-node/blob/59bb3a95784e2a45283c634ec0c716c50520364c/.gitpod.Dockerfile#L41
Perhaps an approach like this is helpful workaround for you.

@WadeBarnes Not sure if the issue with the failing pypi install is known or still an artifact from the old fixed rocksdb version?

**Comment by WadeBarnes** [comment]
Yes, you need to install the dependencies for rocksdb before the pip install.

**Comment by pSchlarb** [comment]
Since a week is gone without further notice i consider this issue closed.
