### ISSUE TITLE
Error when starting pool in docker (mount: permission denied)

### ISSUE THREAD

**Issue by tnkhanh** [hyperledger/indy-node#1765]
Hi, I'm trying to start a pool and encountered this error:
```
# ./pool_start.sh
Creating pool
  
Creating pool of 4 nodes with ips 10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5
Creating a new node Node1 0.0.0.0 9701 0.0.0.0 9702
Setting up docker with systemd
The mount point for the systemd cgroup hierarchy already exists at /sys/fs/cgroup/systemd.
Mounting the systemd cgroup hierarchy.
mount: /sys/fs/cgroup/systemd: permission denied.
```

I have my user in the docker group and can run some other docker containers fine.
I'm on Ubuntu 21.10.
What am I missing?
Thanks!

**Comment by tnkhanh** [comment]
I still have this issue. `/sys/fs/cgroup` and `/sys/fs/cgroup/systemd` are owned by root.
Should I run the pool as root?

**Comment by wiredhikari** [comment]
I faced the similar issue, I fixed it with following steps:
- Run the mount command with sudo: sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
- If the above command doesn't work, check if the cgroup file system is mounted. You can check it by running the command mount | grep cgroup. If it's not mounted, mount it with the following command: sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
