### ISSUE TITLE
Can't Install Indy Node

### ISSUE THREAD

**Issue by fakoberer** [hyperledger/indy-node#1792]
Hi to All!
Although I managed to Indy-sdk and ran code, I am facing problems with installing hyperledger-indy node. When I run the following code block:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
sudo bash -c 'echo "deb https://repo.sovrin.org/deb xenial stable" >> /etc/apt/sources.list'
sudo apt-get update
sudo apt-get install indy-node`

I get an error like given below:
<img width="585" alt="Capture" src="https://user-images.githubusercontent.com/68019897/211720128-3a3a7438-e596-4535-b212-b584289b9151.PNG">

Any help is appreciated! Thanks in advance,

**Comment by pSchlarb** [comment]
I think the exact same problem has already been answered on the discord channel for indy:
I will close this issue for now, if any further problems arise feel free to reopen it. 


https://discord.com/channels/905194001349627914/966347413071728711/966378370260680726

>Indy node /plenum depends on fixed versions of packages, but since there are newer version of that packages in the official repos apt is complaining.

>Chaining the cmd together like sudo apt install indy-plenum=1.13.0~dev175 python3-libnacl=1.6.1 python3-sortedcontainers=1.5.7 works. 
>I am not quite shure if that helps here, since it says not installable but it is a lead.
However Inside the gitpod/workspace-full container, which is derived from the ubuntu 20.04 container  it is working
```
$ sudo apt install indy-node
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  indy-plenum
The following NEW packages will be installed:
  indy-node indy-plenum
0 upgraded, 2 newly installed, 0 to remove and 44 not upgraded.
Need to get 1,630 kB of archives.
After this operation, 7,696 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
```


>According to https://unix.stackexchange.com/questions/350192/apt-get-not-properly-resolving-a-dependency-on-a-fixed-version-in-a-debian-ubunt

    The apt resolver does not consider the possibility that you might want to install something that is not the most recent >available version of a package in a given target release; Debian just doesn't support installing anything but the most up to date >version of a package for your system.

    If you're using different repositories for each version of a (set of) package(s), then you can use pinning to prefer a given >origin, or give them a different codename and use apt's -t option to select the target release. Otherwise it's just not possible.
