### ISSUE TITLE
Install with pip of indy-node fails.

### ISSUE THREAD

**Issue by terilenard** [hyperledger/indy-node#1802]
I am following the guide [Create a Network and Start Nodes](https://github.com/hyperledger/indy-node/blob/ubuntu-20.04-upgrade/docs/source/start-nodes.md) , and wanted to install via pip indy-node. The installation gives the error below. Please find below the steps took to generate the error.

This was ran on a clean virtual machine running ubuntu server 22.04. The install was tested in a python venv and without the venv. Output from uname:

`
Linux charlie 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`
pip version:

`
pip 22.0.2 from /home/teri/Workdir/ssi/lib/python3.10/site-packages/pip (python 3.10)
`

Running:
`(ssi) teri@charlie:~/Workdir/ssi$ pip install indy-node
`
generates the following output:

`(ssi) teri@charlie:~/Workdir/ssi$ pip install indy-node
Collecting indy-node
  Using cached indy-node-1.12.6.tar.gz (475 kB)
  Preparing metadata (setup.py) ... done
Collecting distro==1.3.0
  Using cached distro-1.3.0-py2.py3-none-any.whl (16 kB)
Collecting indy-plenum==1.12.6
  Using cached indy-plenum-1.12.6.tar.gz (930 kB)
  Preparing metadata (setup.py) ... done
Collecting timeout-decorator==0.4.0
  Using cached timeout-decorator-0.4.0.tar.gz (4.7 kB)
  Preparing metadata (setup.py) ... done
Collecting base58==1.0.0
  Using cached base58-1.0.0.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Collecting indy-crypto==0.4.5
  Using cached indy_crypto-0.4.5.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... done
Collecting intervaltree==2.1.0
  Using cached intervaltree-2.1.0.tar.gz (38 kB)
  Preparing metadata (setup.py) ... done
Collecting ioflo==1.5.4
  Using cached ioflo-1.5.4.tar.gz (228 kB)
  Preparing metadata (setup.py) ... done
Collecting jsonpickle==0.9.6
  Using cached jsonpickle-0.9.6.tar.gz (67 kB)
  Preparing metadata (setup.py) ... done
Collecting leveldb
  Using cached leveldb-0.201.tar.gz (236 kB)
  Preparing metadata (setup.py) ... done
Collecting libnacl==1.6.1
  Using cached libnacl-1.6.1-py2.py3-none-any.whl (14 kB)
Collecting msgpack-python==0.4.6
  Using cached msgpack-python-0.4.6.tar.gz (116 kB)
  Preparing metadata (setup.py) ... done
Collecting orderedset==2.0
  Using cached orderedset-2.0.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Collecting packaging==19.0
  Using cached packaging-19.0-py2.py3-none-any.whl (26 kB)
Collecting pip<10.0.0
  Using cached pip-9.0.3-py2.py3-none-any.whl (1.4 MB)
Collecting portalocker==0.5.7
  Using cached portalocker-0.5.7.tar.gz (7.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /home/teri/Workdir/ssi/lib/python3.10/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      error in portalocker setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by pSchlarb** [comment]
Installing purely with pip is known to fail. Have a look and the devcontainerfiles or better the current github actions pipeline definition in the ubuntu20 branch.
Quick tipp install the deb package after adding the repositories to get all the needed dependencies. Though the dependency fixes are currently only in the latest `dev` (1.13.2~dev1678195950) release.

**Comment by pSchlarb** [comment]
Will close this issue. If any further questions arise feel free to reopen or check out the discord
