### ISSUE TITLE
Documentation: For adding a custom transaction type in indy nodes

### ISSUE THREAD

**Issue by georgepadayatti** [hyperledger/indy-node#1806]
Is developer documentation to support custom transaction types in indy nodes available ?

**Comment by WadeBarnes** [comment]
@cjhowland, @dbluhm, You may be the best equipped at the moment to answer this question.

**Comment by dbluhm** [comment]
I'm not currently aware of any docs for writing new transactions (and we're not currently in a position to produce such docs, unfortunately) but we have given a workshop on getting started developing on Indy Node in the past. You can find that here: https://wiki.hyperledger.org/display/events/Hyperledger+Indy+Technical+Deep+Dive

I would study the request handlers for writing a nym (https://github.com/hyperledger/indy-node/blob/main/indy_node/server/request_handlers/domain_req_handlers/nym_handler.py) and reading a nym (https://github.com/hyperledger/indy-node/blob/main/indy_node/server/request_handlers/read_req_handlers/get_nym_handler.py). Hopefully that gives you at least a head start in the right direction!
