### ISSUE TITLE
Create release v1.13.2

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/indy-node#1828]
Create an official v1.13.2 release.

Review and update release docs as needed.

Dependencies:
- https://github.com/hyperledger/indy-plenum/issues/1645

**Comment by WadeBarnes** [comment]
PR to update release documentation; https://github.com/hyperledger/indy-node/pull/1834

**Comment by WadeBarnes** [comment]
Release started by creating the pushing a tag, `setRelease-v1.13.2`, as documented.

Resulting in the triggering of this workflow; https://github.com/hyperledger/indy-node/actions/runs/7819565198.  Which failed.  PR https://github.com/hyperledger/indy-node/pull/1835 contains the fix.

**Comment by WadeBarnes** [comment]
Release restarted by deleting and then creating and pushing the tag, `setRelease-v1.13.1`, as documented.

Resulting in the triggering of this workflow; https://github.com/hyperledger/indy-node/actions/runs/7820881999.

Which in turn created this release PR https://github.com/hyperledger/indy-node/pull/1837, and associated release workflow; https://github.com/hyperledger/indy-node/actions/runs/7820900891

**Comment by WadeBarnes** [comment]
Some additional updates were required to support the build and testing:
- https://github.com/hyperledger/indy-shared-gha/pull/28
- https://github.com/hyperledger/indy-shared-gha/pull/29
- https://github.com/hyperledger/indy-test-automation/pull/132
- https://github.com/hyperledger/indy-test-automation/pull/133
- https://github.com/hyperledger/indy-test-automation/pull/134
- https://github.com/hyperledger/indy-test-automation/pull/135

**Comment by WadeBarnes** [comment]
Release [v1.13.2](https://github.com/hyperledger/indy-node/releases/tag/v1.13.2) created successfully.

Artifacts published to:
- https://hyperledger.jfrog.io/ui/repos/tree/General/indy/pool/focal/stable
- https://pypi.org/project/indy-node/1.13.2/

**Comment by swcurran** [comment]
Nice!
