### ISSUE TITLE
On installation of indy-node with the latest commit we are facing async not found issue

### ISSUE THREAD

**Issue by wiredhikari** [hyperledger/indy-node#1842]
![image](https://github.com/hyperledger/indy-node/assets/81508805/185c3f30-4514-4c64-9293-5fab5a9ee447)

**Comment by WadeBarnes** [comment]
@wiredhikari, Are you installing indy-node for development purposes, or are you trying to setup an indy-node server?  If for development, please use the VS Code or Gitpod dev containers.  If for setting up an indy-node server, please install using the ded packages.

When installing the python packages directly, it's possible you're running into a dependency issue.  Either missing or too new.  You could have a look at the installation process used by the dev containers to try to troubleshoot.

**Comment by wiredhikari** [comment]
Hey @WadeBarnes , I tried exploring devcontainers then found out python 3.10.0 worked out better, so issue is resolved now. Thanks for help

**Comment by WadeBarnes** [comment]
@wiredhikari, Would you be able to share your experience using python 3.10?

**Comment by wiredhikari** [comment]
Sure, so after having installed rocksdb from source and doing some hacks around it: python 3.10.0 works well. The only issue i have faced so far is, nodes arent able to run on certain ports (for me 0.0.0.0:9701 and 0.0.0.0:9702) , but upon changing them, it is working well

**Comment by WadeBarnes** [comment]
> Sure, so after having installed rocksdb from source and doing some hacks around it: python 3.10.0 works well. The only issue i have faced so far is, nodes arent able to run on certain ports (for me 0.0.0.0:9701 and 0.0.0.0:9702) , but upon changing them, it is working well

Anything you can contribute back to the project?
