### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by NidhishVyas** [hyperledger/indy-node#1843]
While setting up the repository, it is throwing an error "ModuleNotFoundError: No module named indy-node"

**Comment by WadeBarnes** [comment]
Please provide more details, such as the steps you're taking that lead up to the reported error message.  Thanks

**Comment by NidhishVyas** [comment]
Hey, I managed to figure that out. I was facing another issue though. Was trying the build from csv in performance folder as well in scripts folder. But where can I generate the csv metric for the graph of the performance of my node. Thanks

**Comment by WadeBarnes** [comment]
> Hey, I managed to figure that out. I was facing another issue though. Was trying the build from csv in performance folder as well in scripts folder. But where can I generate the csv metric for the graph of the performance of my node. Thanks

Please open another ticket for this issue and provide some additional details of what you're trying to accomplish.  The more details you provide the easier it will be for someone to provide you with guidance.
