### ISSUE TITLE
Indy Node Performance Script Check Genesis Error

### ISSUE THREAD

**Issue by SuryaSHalwasia** [hyperledger/indy-node#1845]
Here's the error
Traceback (most recent call last):
  File "perf_processes.py", line 454, in check_genesis
    loop.run_until_complete(pool.create_pool_ledger_config(pool_name, pool_cfg))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/indy/pool.py", line 36, in create_pool_ledger_config
    res = await do_call('indy_create_pool_ledger_config',
indy.error.CommonInvalidStructure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "perf_processes.py", line 505, in <module>
    check_genesis(dict_args["genesis_path"])
  File "perf_processes.py", line 457, in check_genesis
    raise argparse.ArgumentTypeError(ex)
argparse.ArgumentTypeError

Its caused by this line
def check_genesis(gen_path):
    loop = asyncio.get_event_loop()
    pool_cfg = json.dumps({"genesis_txn": gen_path})
    pool_name = "pool_{}".format(random_string(24))
    loop.run_until_complete(pool.set_protocol_version(2))
    try:
        loop.run_until_complete(pool.create_pool_ledger_config(pool_name, pool_cfg))
        pool_handle = loop.run_until_complete(pool.open_pool_ledger(pool_name, None))
    except Exception as ex:
        raise argparse.ArgumentTypeError(ex)
        
 I have provided the pool_transaction_genesis of my hosted von-network. Why exactly is this error coming and how should i fix it? Thanks

**Comment by WadeBarnes** [comment]
Can you please provide the steps you are following that lead up to the reported error message.  Thanks.

**Comment by SuryaSHalwasia** [comment]
Extremely sorry for my late response. Earlier I had provided the genesis file for my von-network. Now, basically I started a indy-node using the indy-node script. In the scripts/performance/perf-load Im running the perf-processes with the genesis transaction path in the sandbox. I have fixed some json parsing errors and now am getting 



User
make it proper json for python
ChatGPT
Certainly! Here's an example of a proper JSON object in Python syntax:

python
Copy code
import json

# Define a Python dictionary
data = {
    "name": "John",
    "age": 30,
    "city": "New York"
}

# Convert the dictionary to JSON
json_data = json.dumps(data)

# Print the JSON
print(json_data)
This will output:

json
Copy code
{"name": "John", "age": 30, "city": "New York"}
This JSON data can be easily parsed and used in Python.

User
just fucking make it into a dictionary 
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"127.0.0.1","client_port":9702,"node_ip":"127.0.0.1","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"}

ChatGPT
Here's the provided JSON string converted into a Python dictionary:

python
Copy code
data = {
    "reqSignature": {},
    "txn": {
        "data": {
            "data": {
                "alias": "Node1",
                "blskey": "4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba",
                "blskey_pop": "RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1",
                "client_ip": "127.0.0.1",
                "client_port": 9702,
                "node_ip": "127.0.0.1",
                "node_port": 9701,
                "services": ["VALIDATOR"]
            },
            "dest": "Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"
        },
        "metadata": {"from": "Th7MpTaRZVRYnPiabds81Y"}
    },
    "type": "0"
}

print(data)
This dictionary represents the JSON object you provided, and you can access its elements like any other Python dictionary.

User
jsons = r'''{
    "reqSignature": {},
    "txn": {
        "data": {
            "data": {
                "alias": "Node1",
                "blskey": "4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSE>
                "blskey_pop": "RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1ag>
                "client_ip": "127.0.0.1",
                "client_port": 9702,
                "node_ip": "127.0.0.1",
                "node_port": 9701,
                "services": ["VALIDATOR"]
            },
            "dest": "Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"
        },
        "metadata": {"from": "Th7MpTaRZVRYnPiabds81Y"}
    },
    "type": "0"
}'''

ChatGPT
Here's the provided JSON string stored in the variable jsons as a Python dictionary:

python
Copy code
import json

jsons = r'''{
    "reqSignature": {},
    "txn": {
        "data": {
            "data": {
                "alias": "Node1",
                "blskey": "4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba",
                "blskey_pop": "RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1",
                "client_ip": "127.0.0.1",
                "client_port": 9702,
                "node_ip": "127.0.0.1",
                "node_port": 9701,
                "services": ["VALIDATOR"]
            },
            "dest": "Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"
        },
        "metadata": {"from": "Th7MpTaRZVRYnPiabds81Y"}
    },
    "type": "0"
}'''

# Parse the JSON string into a Python dictionary
data = json.loads(jsons)

print(data)
This will give you a Python dictionary representing the JSON data stored in the jsons variable.

User
Traceback (most recent call last):
  File "perf_processes.py", line 500, in <module>
    check_genesis(dict_args["genesis_path"])
  File "perf_processes.py", line 449, in check_genesis
    loop.run_until_complete(pool.set_protocol_version(2))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/indy/pool.py", line 212, in set_protocol_version
    res = await do_call('indy_set_protocol_version',
  File "/usr/local/lib/python3.8/dist-packages/indy/libindy.py", line 30, in do_call
    err = getattr(_cdll(), name)(command_handle,
  File "/usr/local/lib/python3.8/dist-packages/indy/libindy.py", line 133, in _cdll
    _cdll.cdll = _load_cdll()
  File "/usr/local/lib/python3.8/dist-packages/indy/libindy.py", line 165, in _load_cdll
    raise e
  File "/usr/local/lib/python3.8/dist-packages/indy/libindy.py", line 160, in _load_cdll
    res = CDLL(libindy_name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libindy.so: cannot open shared object file: No such file or directory

I have not made any change to the program or any other file.
Thanks for your help and sorry again for my late response.

**Comment by WadeBarnes** [comment]
Please provide the steps you are following that lead up to the reported error message; "Step to Reproduce". Thanks.

**Comment by SuryaSHalwasia** [comment]
1. So I started an indy-node using generate_indy_pool_transactions. I create a single node for testing. 
2. I'm in the scripts/performance/perf_load. I started the python3 perf_processes.py -n 1000 -k nym. 
3. In the perf_processes I changed ~/.indy-cli/networks/sandbox/pool_transactions_genesis  to ~/../var/lib/indy/sandbox/pool_transactions_genesis where my genesis file is stored. 
So, these were my steps.

**Comment by WadeBarnes** [comment]
> 1. So I started an indy-node using generate_indy_pool_transactions. I create a single node for testing.

Single node? Or, single pool (network)?  You need at least 4 nodes to form a functional pool (network).

**Comment by SuryaSHalwasia** [comment]
I also tried with a hosted von-network with 4 nodes and go the same error. Earlier I created a folder ~/.indy-cli/networks/sandbox/ and put the transaction genesis file of my hosted von-network but got the error

Traceback (most recent call last):
File "perf_processes.py", line 454, in check_genesis
loop.run_until_complete(pool.create_pool_ledger_config(pool_name, pool_cfg))
File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/home/ubuntu/.local/lib/python3.8/site-packages/indy/pool.py", line 36, in create_pool_ledger_config
res = await do_call('indy_create_pool_ledger_config',
indy.error.CommonInvalidStructure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "perf_processes.py", line 505, in
check_genesis(dict_args["genesis_path"])
File "perf_processes.py", line 457, in check_genesis
raise argparse.ArgumentTypeError(ex)
argparse.ArgumentTypeError

Its caused by this line
def check_genesis(gen_path):
loop = asyncio.get_event_loop()
pool_cfg = json.dumps({"genesis_txn": gen_path})
pool_name = "pool_{}".format(random_string(24))
loop.run_until_complete(pool.set_protocol_version(2))
try:
loop.run_until_complete(pool.create_pool_ledger_config(pool_name, pool_cfg))
pool_handle = loop.run_until_complete(pool.open_pool_ledger(pool_name, None))
except Exception as ex:
raise argparse.ArgumentTypeError(ex)

Thanks

**Comment by SuryaSHalwasia** [comment]
Okay I'll try again. Thanks.

**Comment by SuryaSHalwasia** [comment]
So I got the genesis file right. But now there is no error but the script just runs without any success or failure. I'm sure the ledger is running cause earlier I had gotten pool connection timeout errors.
The script just runs until i forcefully quit with 0 success 0 failure.
Version                   1.2.0
Number of client          4
Path to genesis txns file /root/../var/lib/indy/sandbox/pool_transactions_genesis
Seed                      ['000000000000000000000000Trustee1']
Batch size                1000
Request kind              nym
Refresh rate, sec         10
Pregenerated reqs cnt     30
Output directory          ./load_test_20240315_161322
Value Separator           |
Wallet Key                key
Started At                2024-03-15 16:13:22.478013
Mode                      processes
Sync mode                 freeflow
Pool config               None
Load rate batches per sec 10.0
Ext settings              None
Save short statistics     False
2944.08 Clients 0/4 Sent: 0 Succ: 0 Failed: 0 Nacked: 0 Rejected: 0

Thanks

**Comment by WadeBarnes** [comment]
You'll have to play around with the input parameters a little bit.  Try reducing the number of transactions to start.

I find you typically have to specify:
- a client count, `-c`
- the path to the genesis file, `-g`
- a seed for the DID that has permissions in the ledger, `-s`

**Comment by SuryaSHalwasia** [comment]
Thanks the program is working. However I'm only able to make it for locally running von-networks. Is there a port I should open for the client so I can connect it to von-network running on cloud? Thanks

**Comment by WadeBarnes** [comment]
You would need to use the genesis file for the network you'd like to test.  For ports, Indy uses anything in the range of 9700 to 9799.  The exact ports depend on the network and the nodes on that network.  Please DO NOT run performance tests against any of the BCovrin Ledgers such as BCovrin Text (http://test.bcovrin.vonx.io/).  The performance tests can add 10s to 100s of thousands of transactions to a Ledger  bloating it unnecessarily.

**Comment by SuryaSHalwasia** [comment]
Okay thanks for your help.
